/* boards.js: the boards the viewer (index.html) lays out, one row per route, desktop beside phone.
 * Generated by gen.py from its ROUTES table; edit that, not this. The viewer reads this file through
 * a <script> tag because Chrome blocks fetch() on file:// URLs and the viewer opens from disk.
 * A listed file that is missing renders as a visible warning tile, never a blank one. */
window.WIREFRAME_BOARDS = [
  { label: 'Conversation · Needs you · questions upfront', desktop: 'ConversationFirstNeedsYou.html', mobile: 'MobileConversationFirstNeedsYou.html' },
  { label: 'Conversation · One question · answer in place', desktop: 'ConversationFirstQuestion.html', mobile: 'MobileConversationFirstQuestion.html' },
  { label: 'Conversation · Choose answers · send once', desktop: 'ConversationFirstGroup.html', mobile: 'MobileConversationFirstGroup.html' },
  { label: 'Conversation · Discuss without deciding', desktop: 'ConversationFirstFollowup.html', mobile: 'MobileConversationFirstFollowup.html' },
  { label: 'Conversation · Keep only what still needs an answer', desktop: 'ConversationFirstPartial.html', mobile: 'MobileConversationFirstPartial.html' },
  { label: 'Conversation · Decisions recorded · work resumed', desktop: 'ConversationFirstAccepted.html', mobile: 'MobileConversationFirstAccepted.html' },
  { label: 'Conversation · Shared input and recovery appendix', desktop: 'ConversationFirstStates.html', mobile: 'MobileConversationFirstStates.html' },
  { label: 'Project: chat with L3, work panel beside it', desktop: 'Project.html', mobile: 'MobileProject.html' },
  { label: 'Project switcher (phone)', mobile: 'MobileSwitcher.html' },
  { label: 'Project work (phone)', mobile: 'MobileWork.html' },
  { label: 'Task page: L2 conversation and live session', desktop: 'Task.html', mobile: 'MobileTask.html' },
  { label: 'Task live session (phone)', mobile: 'MobileTaskLive.html' },
  { label: 'Task live panel overlay below 1280px', desktop: 'TaskOverlay.html', desktopSize: { w: 1100, h: 900, name: 'Sheet' } },
  { label: 'Task page states', desktop: 'TaskStates.html', desktopSize: { w: 1200, h: 2260, name: 'Sheet' } },
  { label: 'Report and digest', desktop: 'Report.html', mobile: 'MobileReport.html' },
  { label: 'Monitor', desktop: 'Monitor.html', mobile: 'MobileMonitor.html' },
  { label: 'Monitor states', desktop: 'MonitorStates.html', desktopSize: { w: 1200, h: 1180, name: 'Sheet' } },
  { label: 'Restart banner states', desktop: 'RestartStates.html', desktopSize: { w: 1200, h: 540, name: 'Sheet' } },
  { label: 'First run', desktop: 'FirstRun.html' },
  { label: 'Composer states, voice included', desktop: 'ComposerStates.html', desktopSize: { w: 1200, h: 1380, name: 'Sheet' } },
  { label: 'Voice input states: desktop and phone', desktop: 'VoiceStates.html', desktopSize: { w: 1200, h: 2700, name: 'Sheet' } },
  { label: 'Settings', desktop: 'Settings.html', mobile: 'MobileSettings.html' },
  { label: 'Settings · Voice input', desktop: 'VoiceSettings.html', mobile: 'MobileVoiceSettings.html' },
  { label: 'Settings · This project', desktop: 'ProjectSettings.html', mobile: 'MobileProjectSettings.html' },
  { label: 'Settings states and entry points', desktop: 'SettingsStates.html', desktopSize: { w: 1200, h: 3460, name: 'Sheet' } },
  { label: 'Models dialog states', desktop: 'ModelsStates.html', desktopSize: { w: 1200, h: 2340, name: 'Sheet' } },
  { label: 'System turns in chat: reports, faults, FYIs', desktop: 'SystemTurnStates.html', desktopSize: { w: 1200, h: 1100, name: 'Sheet' } },
  { label: 'Conversation and report states', desktop: 'ConversationStates.html', desktopSize: { w: 1200, h: 740, name: 'Sheet' } },
  { label: 'Project lifecycle states', desktop: 'ProjectLifecycleStates.html', desktopSize: { w: 1200, h: 1400, name: 'Sheet' } },
];

/* Native sizes, matching shots.sh (which reads each board's own width and height). A row's
 * desktopSize / mobileSize ({ w, h, name }) overrides these for that row. */
window.WIREFRAME_SIZES = {
  desktop: { w: 1440, h: 900, name: 'Desktop' },
  mobile:  { w: 390,  h: 844, name: 'iPhone' },
};
